### ISSUE TITLE
长时间连接后似乎会出现心跳包发送失败, 或者未发送失败但无法接收到任何消息的情况

### ISSUE THREAD

**Issue by Megghy** [is-a-gamer/BilibiliUtilities#4]
发生的时间也不是很确定, 有时候一会儿就没反应了, 有时又能跑很久
在几个网络环境下测试都有概率发生
运行环境是.net6, winserver
调试输出里会报
 ```
引发的异常:“Newtonsoft.Json.JsonReaderException”(位于 Newtonsoft.Json.dll 中)
引发的异常:“Newtonsoft.Json.JsonReaderException”(位于 BilibiliUtilities.Live.dll 中)
引发的异常:“System.IO.IOException”(位于 BilibiliUtilities.Live.dll 中)
```

**Comment by bitwasd** [comment]
邮件已收到，我会尽快回复的。我是YJ，请确认有没有发错。

**Comment by 0xKaeruIO** [comment]
感谢反馈

**Comment by 0xKaeruIO** [comment]
项目早已暂停, B站官方SDK也已经支持Unity,此项目将存档,如有类似需求，请前往 [哔哩哔哩直播开放平台](https://open-live.bilibili.com/) 查看 [SDK For Unity](https://open-live.bilibili.com/document/cca272c5-e49d-6bea-0fbe-23c37288a08a)
